# Generated by Django 4.2.4 on 2023-09-04 04:50

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='product/img/no_image.png', upload_to=product.models.product_main_image),
        ),
    ]
