# Generated by Django 4.2.4 on 2023-09-09 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('product', '0004_product_weight_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='session_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
