# Generated by Django 4.2.4 on 2023-09-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
